apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld
  namespace: istio-system
spec:
  hosts:
  - hello.world.cloud.com
  gateways:
  - cloud-gateway
  http:  
    - uri:
        prefix: /   
    route:
    - destination:
        host: hello-world
        port:
          number: 8080
