apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"cloud-dev"},"name":"hello-world","namespace":"argocd"},"spec":{"ports":[{"port":8080,"targetPort":8080}],"selector":{"app":"hello-world"}}}
  
  labels:
    app.kubernetes.io/instance: cloud-dev
  name: hello-world
  namespace: argocd  
spec:
  clusterIP: 100.67.16.114
  clusterIPs:
  - 100.67.16.114
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31892
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
