apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-virtual-service
  namespace: istio-system
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:  
    route:
    - destination:
        host: hello-world
        port:
          number: 8080
