apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-virtual-service
  namespace: istio-system
spec:
  hosts:
  - hello.cloud.com
  gateways:
  - bookinfo-gateway
  http:  
    route:
    - destination:
        host: hello-world.default.svc.cluster.local
        port:
          number: 8080
